application: subway-spb
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /javascripts
  static_dir: javascripts

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /images
  static_dir: images

- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: metro.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest